### ISSUE TITLE
Consider describing test configurations using a JDL file

### ISSUE THREAD

**Issue by PierreBesson** [hipster-labs/jhipster-daily-builds#1]
For example, see @deepu105's sample JDL file : https://gist.github.com/deepu105/8e568eb7b5b5e3c00af0fdf3d2cf71ba
This would be really convenient to describe a full microservice architecture and for easily reproducing locally.

**Comment by deepu105** [comment]
May be you could write a shell or nodejs script that will execute the
import jdl and then go into each directory and run the build and test
commands.

**Comment by pascalgrimaud** [comment]
yes it's the idea !!! I'd love to have it, to secure our release. 
There is only the same problem: I need time :)

But no worry, it will be done

**Comment by pascalgrimaud** [comment]
@Hawkurane : I just updated all scheduler. All the current builds will run between 0:00 UTC and 8:30 UTC. So you can start the new builds at 9:00 UTC.
I'll let you configure the new JDL schedulers. Let me know if you need help.

Then, once it's configured, we can close this ticket !
