### ISSUE TITLE
Too many failing builds

### ISSUE THREAD

**Issue by deepu105** [hipster-labs/jhipster-daily-builds#115]
I was looking into failing builds after the recent react migrations https://github.com/jhipster/generator-jhipster/pull/15191 and https://github.com/jhipster/generator-jhipster/pull/15106 and found that there are many other failing builds as well with weird errors

Many failures seems to be during e2e tests. The angular protractor e2e tests are also failing and the above migrations havent touched those so it needs investigation. Also the React e2e were fixed in recent commits but the repo here seems to use old code anyway. @pascalgrimaud is there some sort of cache here?

Overall I might need more help here @pascalgrimaud @DanielFran @mshima @SudharakaP

**Comment by pascalgrimaud** [comment]
No cache, excepting maybe for maven libs, but I don't think it's related

**Comment by deepu105** [comment]
For somereason the error is from before my fixes for example [this](https://github.com/hipster-labs/jhipster-daily-builds/runs/2733824540?check_suite_focus=true#step:18:445) shouldnt happen anymore as I removed those expect calls in templates so dont know how it still does it. Lemme try to replicate this locally

**Comment by mshima** [comment]
It turns out that proctrator is conflicting with chrome 91.
There is no specific commit that broke daily builds.

**Comment by deepu105** [comment]
@mshima but not for all builds I think, todays builds are running with some failures like I mentioned above

**Comment by mshima** [comment]
@deepu105 the build you mentioned is before your PR. The correct is https://github.com/hipster-labs/jhipster-daily-builds/runs/2742805106.

**Comment by deepu105** [comment]
ah shit sorry

**Comment by deepu105** [comment]
anyway we need to work on this so i'm putting a bounty on this

**Comment by deepu105** [comment]
also should we switch to cypress for some tests instead of protractor ?

**Comment by pascalgrimaud** [comment]
@deepu105 : I mixed both, protractor for default builds, cypress for JDL

**Comment by mshima** [comment]
@deepu105 you fixed on react side with https://github.com/jhipster/generator-jhipster/commit/11dfed8466ff69d017d94bfe0b4773421173bf8f#diff-c14159cc6cbb565f01325eed42e2932a5c0fe58c47a93ed84bea30fa41dcfa6c.

Should be applied to angular and vue?
Any clue why this was required?

**Comment by deepu105** [comment]
I have no idea why it was added. Ideally it shouldn't be there as its a bad
practice to do expect in page objects IMO

**Comment by mshima** [comment]
I've deployed a workaround at https://github.com/jhipster/generator-jhipster/pull/15227.

Fix is merged but not released yet: https://bugs.chromium.org/p/chromium/issues/detail?id=1205107&start=300Upstream
protractor issue: https://github.com/angular/protractor/issues/5519

We should revert the workaround once the fix is released.

**Comment by deepu105** [comment]
Doesnt removing the expect checks in the page objects work? IMO they should
be removed as they dont server any purpose other then verifying if
protractor can input text to field and its not our responsibility to check
that. So we should remove those checks any way

Thanks & Regards,
Deepu

**Comment by pascalgrimaud** [comment]
Not sure, but if I remember well, these additional checks were there to fix the random failures we got in the past

**Comment by pascalgrimaud** [comment]
Still some errors with **React + i18n** :

![image](https://user-images.githubusercontent.com/9156882/121643815-8d531380-ca92-11eb-9b9f-99a331585d33.png)

![image](https://user-images.githubusercontent.com/9156882/121643852-9643e500-ca92-11eb-8541-d3d1b4a437e7.png)

**Comment by pascalgrimaud** [comment]
My investigation led me to https://github.com/jhipster/generator-jhipster/commit/24e089448a9a36c86d72fa2ac307bfb54cf0303a#diff-86124b7420820701b49181ce2aa6a3cb0dd3731cea2937e32311ae19b7393cf5 and specially at:

![image](https://user-images.githubusercontent.com/9156882/121654133-b2994f00-ca9d-11eb-971a-6a7de5e687e3.png)

It explains the NPE in the backend, which could be fixed by something like:

```java
    private String getLangKey(User user) {
        return Optional.ofNullable(user.getLangKey()).orElse("en");
    }
```

Anyway, the failures are still there, as it concerns the front part.
Can I let you have a look @deepu105 ? Not sure I can solve the React part.

**Comment by deepu105** [comment]
I made a PR. It should fix the React builds

Thanks & Regards,
Deepu

**Comment by pascalgrimaud** [comment]
Everything is OK now !
we can close this. Don't forget to claim your bounty @deepu105

**Comment by deepu105** [comment]
I think @mshima and you also fixed some stuff right? So we should share the bounty

**Comment by deepu105** [comment]
may be we can each claim 100

**Comment by pascalgrimaud** [comment]
Just added a new label, to increase the bounty.
Now you can share :-)

**Comment by deepu105** [comment]
why 400 is there another person who worked on this apart form the 3 of us?

**Comment by mshima** [comment]
> My investigation led me to [jhipster/generator-jhipster@24e0894#diff-86124b7420820701b49181ce2aa6a3cb0dd3731cea2937e32311ae19b7393cf5](https://github.com/jhipster/generator-jhipster/commit/24e089448a9a36c86d72fa2ac307bfb54cf0303a#diff-86124b7420820701b49181ce2aa6a3cb0dd3731cea2937e32311ae19b7393cf5) and specially at:

Nice find, I was thinking the problem were sass builds not i18n.

For reference the PR that fixed some builds is https://github.com/jhipster/generator-jhipster/pull/15245.

I am planning to add cache to reduce random failures soon.

**Comment by deepu105** [comment]
@mshima please claim 200 for your PR

**Comment by deepu105** [comment]
Seems like he doesn't want to claim, but I think he should 😉

**Comment by mshima** [comment]
@deepu105 😆.
I accept then.
This problem got me in the middle of the https://github.com/hipster-labs/jhipster-daily-builds/pull/117.

**Comment by deepu105** [comment]
here is my part https://opencollective.com/generator-jhipster/expenses/42841

**Comment by pascalgrimaud** [comment]
@deepu105 : approved

**Comment by mshima** [comment]
@pascalgrimaud half bounty claimed https://opencollective.com/generator-jhipster/expenses/42842

**Comment by pascalgrimaud** [comment]
@mshima : approved
