### ISSUE TITLE
installing Jhipster IDE from STS marketplace is encountering problem

### ISSUE THREAD

**Issue by shajahank1** [hipster-labs/jhipster-daily-builds#123]
Tried to install the Jhipster IDE 2.3.5 from Spring Tool Suite 4 
(Version: 4.10.0.RELEASE,Build Id: 202103111225)  eclipse market place.
But encountered problem . 
Please see the details:

An error occurred while collecting items to be installed
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Artifact not found: osgi.bundle,com.google.inject,3.0.0.v201605172100.
Artifact not found: osgi.bundle,org.apache.commons.cli,1.4.0.v20200417-1444.
Artifact not found: osgi.bundle,org.eclipse.emf,2.8.0.v20180706-1146.
Artifact not found: osgi.bundle,org.eclipse.emf.codegen.ecore,2.25.0.v20201231-0738.
Artifact not found: osgi.bundle,org.eclipse.emf.ecore.editor,2.17.0.v20190528-0725.
Artifact not found: osgi.bundle,org.eclipse.emf.mwe.core,1.6.1.v20210218-2134.
Artifact not found: osgi.bundle,org.eclipse.emf.mwe.utils,1.6.1.v20210218-2134.
Artifact not found: osgi.bundle,org.eclipse.emf.mwe2.lib,2.12.1.v20210218-2134.
Artifact not found: osgi.bundle,org.eclipse.emf.mwe2.runtime,2.12.1.v20210218-2134.

**Comment by pascalgrimaud** [comment]
I don't understand this issue
