### ISSUE TITLE
Watchtower with jhispter

### ISSUE THREAD

**Issue by FrancescoMez79** [hipster-labs/jhipster-daily-builds#138]
Hello,
how can we configure watchtower with jhipster?
We run our jhipster application executing by docker-composite app.yml file.

Can we configure watchtower to automatizate the pull and run of the image?
Thanks,
Francesco

**Comment by mraible** [comment]
Please enter issues or ask questions (in discussions) on the main generator at https://github.com/jhipster/generator-jhipster.
