### ISSUE TITLE
Daily builds for blueprints:

### ISSUE THREAD

**Issue by Hawkurane** [hipster-labs/jhipster-daily-builds#14]
While the blueprints are getting more and more popular and performing, they lack test coverage: some of them cover almost as much as the main generator and it would be great to implement a way to expand the test coverage to these blueprints, here are some ideas:

- Have another Azure organisation for each blueprints (Kotlin ? Vuejs?) and "fork" this repo.
- Add some more daily builds configuration as we still have some "time left" each day to run some more configurations

Related Issues/PR:
- [vuejs](https://github.com/jhipster/jhipster-vuejs/pull/422#issuecomment-509576547)
- #10 

Pinging lord and saviour @pascalgrimaud for input

**Comment by pascalgrimaud** [comment]
Yes it is nice to have but it took time to achieve this...
Let's keep this ticket opened

**Comment by mraible** [comment]
Can we close this now?

**Comment by pascalgrimaud** [comment]
Opened for too long, so yes, let's close this
