### ISSUE TITLE
Add builds for testing Yarn

### ISSUE THREAD

**Issue by pascalgrimaud** [hipster-labs/jhipster-daily-builds#4]
Similar to NPM but with Yarn

**Comment by pvliss** [comment]
@pascalgrimaud I see 2 approaches that can be taken here
1. To add just a few more scripts for testing yarn as in my comment https://github.com/jhipster/generator-jhipster/pull/9452#issuecomment-474293668 
2. Write some kind of script that would alter the existing scripts and replace npm with yarn and run them all

The first one is definitely easier and I am not sure if the second one is doable but could take a look. Maybe you have better idea? What was your initial plan/approach and what approach would you prefer?

**Comment by pascalgrimaud** [comment]
@pvliss :
- in generator-jhipster
    - modify the script [22-tests-frontend.sh](https://github.com/jhipster/generator-jhipster/blob/master/test-integration/scripts/22-tests-frontend.sh)
    - it can read the `.yo-rc.json` file to know if it uses `npm` or `yarn` / or it could be a new global var in this part: https://github.com/jhipster/generator-jhipster/blob/master/azure-pipelines.yml#L24-L39
- in this repo jhipster-daily-builds
    - add a new file azure-pipelines-yarn.yml
    - add some new samples, using `yarn` in https://github.com/hipster-labs/jhipster-daily-builds/tree/master/test-integration/samples
    - once it's merged into master, I can add a new cron in administration settings

Just let me know if you want to do it, so we won't work on the same ticket :)

**Comment by pvliss** [comment]
@pascalgrimaud By all means go ahead. You will definitely do it faster and better :)

**Comment by pascalgrimaud** [comment]
done here https://github.com/hipster-labs/jhipster-daily-builds/commit/df5b928f01881b02bbdd71aa99523e84c83ac9d7

**Comment by pvliss** [comment]
Thanks a lot @pascalgrimaud !!!
