### ISSUE TITLE
Official Windows GitHub CI Failing

### ISSUE THREAD

**Issue by Hawkurane** [hipster-labs/jhipster-daily-builds#44]
Currently, the windows build workflows returns with

> Error when evaluating 'runs-on' for job 'applications'. Unexpected value ''

It seems, it has trouble finding the value 'windows-latest' for the runs-on parameter.
Associated documentation: [https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners](https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners)

**Comment by pascalgrimaud** [comment]
minor comment: the file could be rename by windows.yaml I think

**Comment by Hawkurane** [comment]
Ok, I've just renamed it right now :)

**Comment by pascalgrimaud** [comment]
@Hawkurane : the initial error is fixed. See https://github.com/hipster-labs/jhipster-daily-builds/commit/725ec42f4ed172d77ab343d073a78a93e9c1f8f1

As described in logs, the problem was on the `runs-on`. The matrix was not corrected because the `app-type` was not consistent with `include` part.
