### ISSUE TITLE
Neo4j: disabled

### ISSUE THREAD

**Issue by pascalgrimaud** [hipster-labs/jhipster-daily-builds#45]
Disabled at https://github.com/hipster-labs/jhipster-daily-builds/commit/f5dbe944f0ac606c90b8617fa07898d8e8ac40e6

Waiting to be fixed in main-generator JHipster.
cc @atomfrede -> when it's fixed, we can reactivate it

**Comment by atomfrede** [comment]
Hope to have some time tomorrow.

**Comment by atomfrede** [comment]
The main generator will be fixed by https://github.com/jhipster/generator-jhipster/pull/11581
Would like to make a dedicated sample for neo4j (until we have fixed the performance problem with the bidirectional relationships in the bank account example).

**Comment by atomfrede** [comment]
Test failed with failing assertion. I tried the same configuration locally and it works fine. Will check if I have different application options selected.

**Comment by atomfrede** [comment]
Okay I found a very strange thing. I used the exact same configuration from the daily builds and `mvn verify` really failed with the same error as in ci. I run the test in IDEA and it was green. Afterwards it was also green via `mvn verify` :confounded: I have uploaded the generated sample here if someone can try it https://github.com/atomfrede/neo-daily-build-sample

**Comment by pascalgrimaud** [comment]
@atomfrede : I'll try it soon

**Comment by pascalgrimaud** [comment]
@atomfrede :
- I manage to easily reproduce the same issue in the CI
- sometimes, it failed, sometimes not -> random failures
- we got a similar issue with Cassandra: https://github.com/jhipster/generator-jhipster/issues/11169
- @SudharakaP tried to fix it with https://github.com/jhipster/generator-jhipster/pull/11204

But in the end, the problem is global
- for NoSQL database, each integration tests of our entities depends on "deleteAll" before
- the test needs a clean database to pass
- we don't have the problem with SQL as we used `@Transactional`
- for unknow reason, the deleteAll doesn't executed well and sometimes, as the order is different, the test can fail
- for me, the main refactoring should be done for each tests, which should NOT depends on a clean database

**Comment by atomfrede** [comment]
Interesting didn't think of that. I cloned the sample on my laptop and each time different tests fail. In fact delete all is not called. It looks like adding that to the beforeEach method seems to fix that.

**Comment by atomfrede** [comment]
And finally its green :relieved:

**Comment by atomfrede** [comment]
Will look into the failing webflux build tonight.

**Comment by pascalgrimaud** [comment]
thanks @atomfrede

**Comment by pascalgrimaud** [comment]
already fixed
