### ISSUE TITLE
Couchbase: disabled

### ISSUE THREAD

**Issue by pascalgrimaud** [hipster-labs/jhipster-daily-builds#46]
Disabled at https://github.com/hipster-labs/jhipster-daily-builds/commit/f5dbe944f0ac606c90b8617fa07898d8e8ac40e6

The integration tests are too flatky.
See :
- https://github.com/hipster-labs/jhipster-daily-builds/actions?query=workflow%3A%22Angular+Maven+NoSQL%22
- https://github.com/hipster-labs/jhipster-daily-builds/actions?query=workflow%3A%22Angular+Gradle+NoSQL%22
- https://github.com/hipster-labs/jhipster-daily-builds/actions?query=workflow%3A%22React+Maven+NoSQL%22
- https://github.com/hipster-labs/jhipster-daily-builds/actions?query=workflow%3A%22React+Gradle+NoSQL%22

cc @tchlyah -> as you're our main contributor on Couchbase
cc @SudharakaP -> as I know you already spent a lot of time on this

**Comment by SudharakaP** [comment]
@pascalgrimaud : Let me take another look as well; I think we didn't have a final solution the last time. :smile:

**Comment by pascalgrimaud** [comment]
@SudharakaP :  don't spend time on this, I'm pretty sure it will be fixed soon
See https://github.com/testcontainers/testcontainers-java/pull/2491

**Comment by SudharakaP** [comment]
Thanks for letting me know. :smile:

**Comment by DanielFran** [comment]
@pascalgrimaud should we disable also couchbase on webflux workflow in main generator?

**Comment by pascalgrimaud** [comment]
@DanielFran : if it failed a lot, yes

**Comment by SudharakaP** [comment]
https://github.com/testcontainers/testcontainers-java/pull/2491 is now merged and they release a new version https://github.com/testcontainers/testcontainers-java/releases/tag/1.14.0. But I don't see it on [sonatype yet](https://search.maven.org/search?q=g:org.testcontainers). Does it take some time before it's available? :thinking:

**Comment by SudharakaP** [comment]
Ah now it's available. So I've went ahead and updated it; we shall see if this fixes our problems. :smile:

**Comment by SudharakaP** [comment]
I've upgraded testcontainers and adjusted the Couchbase testing to conform to the new api. Please let me know if you see any issues. :smile:

**Comment by bsideup** [comment]
@SudharakaP I hope the change was painless :) Please let us know if you experience any issues with the new implementation 👍

**Comment by SudharakaP** [comment]
@bsideup ; Thanks Sergei. :smile: Yes it wasn't difficult. We will soon see how the new implementation works when the daily builds starts to run. :smile:
