### ISSUE TITLE
Windows: disabled

### ISSUE THREAD

**Issue by pascalgrimaud** [hipster-labs/jhipster-daily-builds#48]
Disabled at 4be37370f5e064840c5625a556a20cde8159ca6a

cc @Hawkurane : FYI, I disabled it. I think it is useless to let the build running if it failed.

**Comment by SudharakaP** [comment]
Is anyone working on this? I can take a look next week. :smile:

**Comment by pascalgrimaud** [comment]
@SudharakaP : no, plz go ahead !

**Comment by SudharakaP** [comment]
@pascalgrimaud : I've done it. Note that I only included the app-types you've committed at 725ec42f. Let me know if you want to add more app-types for this.
