### ISSUE TITLE
OAuth2: test microservices

### ISSUE THREAD

**Issue by pascalgrimaud** [hipster-labs/jhipster-daily-builds#6]
Following this https://github.com/jhipster/generator-jhipster/pull/9484#issuecomment-477615927

The problem is the `keycloak.yml` file is not generated any more for microservices.
So we can't start a microservice with OAuth2, alone. It needed to be a Gateway.

As a temporary fix, I disabled the run. See my commit: https://github.com/hipster-labs/jhipster-daily-builds/commit/5b8f125131a3d39c190e0572dd60fd4c3d7a44d4

It could be tested back as soon as I finish the multi app, using JDL:
- generate 2 or 3 applications using JDL
- package and create Docker image
- start the full stack, using docker-compose with `app.yml` file

**Comment by Hawkurane** [comment]
I will add a build later specifically for OAuth 2 and OIDC
