### ISSUE TITLE
Add cypress to JDLMs builds.

### ISSUE THREAD

**Issue by Hawkurane** [hipster-labs/jhipster-daily-builds#62]
Now that protractor is considered deprecrated in a JHipster application, we should change from protractor e2e tests to cypress ones.

**Comment by pascalgrimaud** [comment]
Can we keep some builds with Protractor ? Until it is removed completely...

**Comment by Hawkurane** [comment]
It's declared deprecrated by the main generator, when you build an app with both options, it's running the cypress tests only. Unsure if it's worth it to keep protractor, I can add a few builds with protractor though, but I think some of the not-JDLMs builds are running protractor
